info:
 name: zuul-server
 description: Zuul Server
 version: 1.0.0
endpoints:
 restart:
  enabled: true
 shutdown:
  enabled: true
 health:
  enabled: true
  sensitive: false
server:
  port: 8080

zuul:
 routes:
  microservice-one:  
   path: /microserviceone/**
   serviceId: microservice-one
  microservice-two:  
   path: /microservicetwo/**
   serviceId: microservice-two

