info:
  component: Zuul Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    microservice_one:  /microserviceone/**
    #microservicetwo:  /microservicetwo/**

server:
  port: 8080

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
