info:
  name: Eureka Server
  description: Eureka Server
  version: 1.0.0
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    enabled: true
    sensitive: false
management:
  context-path: /manage
security:
  basic:
    enabled: false
server:
  port: 8761
eureka:
  dashboard:
    enabled: true
  instance:
    hostname: localhost
    statusPageUrlPath: ${management.contextPath}/info
    healthCheckUrlPath: ${management.contextPath}/health
    leaseRenewalIntervalInSeconds: 3
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0
      renewalPercentThreshold: 0.49