info:
  name: Eureka Server
  description: Eureka Server
  version: 1.0.0
server:
 port: 8761
---
eureka:
 dashboard:
  enabled: true
 instance:
  hostname: localhost
 client:
  healthcheck:
   enabled: true
  registerWithEureka: false
  fetchRegistry: false
  serviceUrl:
   defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
