#----------------------------------
#
#
#----------------------------------
info:
 name: configserver
 description: configserver
 version: 1.0.0
---
server:
  port: 8888
  
spring:
 cloud:
  config:
   server:
    git:
     uri: https://github.com/cjrequena/config-repo
     #username: gitusername
     #password: gitpassword
     basedir: target/config
         
security:
 user:
  name: user
  password: s3cr3t