info:
  name: configserver
  description: configserver
  version: 0.0.1
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
server:
  port: 8888
  
management:
  context-path: /admin
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
    
---
spring:
   cloud:
      config:
         server:
            git:
               uri: https://github.com/cjrequena/config-repo
               #username: gitusername
               #password: gitpassword
               basedir: target/config
              
security:
  user:
    password: s3cr3t